Ipad 305 favicons triple panel
abbvie-external/OmicNavigatorWebApp pull request #15
Opened 2021-04-29 14:14 UTC by paulnordlund

- adds favicons to the filtered differential table (enrichment tab, triple plot view)

2021-04-29 17:49 UTC, JoeDalen81 requested changes

2021-04-29 17:49 UTC, JoeDalen81 commented on src/components/Enrichment/Enrichment.jsx
> +    debugger;
How'd this guy get in there :)

2021-04-30 16:30 UTC, JoeDalen81 approved these changes

2021-04-30 16:49 UTC, ternst23 approved these changes

2021-04-30 16:49 UTC, merged